### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by ddonindia** [levent/agileista#81]
I am able to setup agileista server on my Ubuntu Linux dev box.
But unable to login/signup. I have tried multiple mail ids but still not able to login.
I didnt received any confirmation mail so to unblock myself I manually updated people table to confirm my user.
But still cant get pass login page :(.

Can you please help.

**Comment by levent** [comment]
Sorry it's not a great onboarding experience yet!
If you log into the rails console, you can find your user and set the password that way.

``` ruby
# bundle exec ./bin/rails console production # or just ./bin/rails c for development environment
person = Person.find_by email: 'you@email.com'
person.password = 'newpassword'
person.password_confirmation = 'newpassword'
person.save!
```

**Comment by ddonindia** [comment]
couldn't get it working :( switched to taiga
